package br.org.carameloCode.erp.modulo.crm.api.model.pessoa;

import br.org.carameloCode.erp.modulo.crm.entidadesJPA.crm.prospecto.Pessoa;
import com.super_bits.modulosSB.SBCore.modulos.objetos.InfoCampos.anotacoes.InfoReferenciaEntidade;

@InfoReferenciaEntidade(tipoObjeto = Pessoa.class)
public enum CPPessoa {
	_ID, _NOME, _DADOSCOLETADOS, _TIPOPESSOA, _DOCUMENTO, _TODOSDADOSCOLETADOS, _TELEFONEPRINCIPAL, _OUTROSTELEFONES, _EMAIL, _ATENDENTELOGADOTEMACESSO, _ATENDENTELOGADORESPONSAVELPRINCIPAL, _UMPERFILPRIVADO, _UMPERFILPUBLICO, _UMPERFILCOMPARTILHADO, _SATISFACAO, _RELACIONAMENTO, _EMAILSENVIADORECEBIDO, _LISTAAPRESENTACOESVINCULADAS, _UMAPESSOAFISICA, _UMAPESSOAJURIDICA, _ENDERECO, _CEP, _ORIGEM, _CONTATOPRINCIPAL, _CONTATOSPROSPECTO, _ARQUIVOS, _ULTIMOSARQUIVOS, _LOCALIZACAO, _SERVICOS, _ULTIMOORCAMENTO, _ORCAMENTOS, _META, _CANALROCKETCHAT, _USUARIOSRESPONSAVEIS, _USUARIOSCONVIDADOS, _USUARIOSRESPDISPONIVEIS, _RELACIONAMENTOANTERIOR, _USUARIORESPONSAVEL, _USUARIOATENDIMENTO, _DATAHORACRIOUPROSPECTO, _DATAHORAALTEROUPROSPECTO, _DATAHORAULTIMAINTERACAO, _USUARIOCRIOU, _USUARIOEDITOU, _QUANTIDADECONTATOS, _QUANTIDADEANEXOS, _QUANTIDADEATIVIDADES, _QUANTIDADEATIVIDADESLEAD, _QUANTIDADEEMAILSTROCADOS, _QUANTIDADEEMAILSNAOLIDOS, _ATIVIDADESEXECUTADAS, _MODOPOSVENDAS, _POSSUIDEMANDAURGENCIA, _DATAHORAMUDANCARELACIONAMENTO, _ATIVIDADESREALIZADAS, _HISTORICORELACIONAMENTO, _ATIVO, _LINKNOTIONINTRANET, _RESPONSAVEL, _OBSERVACAO, _ESTILOVISUALIZACAO, _USUARIOLOGADOSOLICITOUACESSO, _TAGSATENDIMENTO, _POSSUIATIVIDADESEMANDAMENTO, _CLIENTESRELACIONADOS, _CLIENTESQUEMERELACIONAM, _EMAILSENVIADOS, _EMAILSRECEBIDOS, _EMAILSNAOENVIADOS, _EMAILSNAOLIDO, _ATIVIDADESEMANDAMENTO, _LISTADADOSCRM, _RELACIONAMENTOSCOMCOLETADADO, _LISTADADOSCRMPORTIPORELACIONAMENTO, _LISTADADOSCOLETADOSNAOVINCULADOS, _PERTENCEAOUSUARIOLOGADO, _CAMPOSDINAMICOSAGRUPADOS, _ULTIMAATIVIDADEEMANDAMENTO, _DOCEQUIPECATEGORIAS, _DOCCLIENTECATEGORIAS, _INTEGRACOESLINK, _CHAMADOSABERTOS, _SOLICITACOESABERTAS;

	public static final String id = "id";
	public static final String nome = "nome";
	public static final String dadoscoletados = "dadosColetados";
	public static final String tipopessoa = "tipoPessoa";
	public static final String documento = "documento";
	public static final String todosdadoscoletados = "todosdadosColetados";
	public static final String telefoneprincipal = "telefonePrincipal";
	public static final String outrostelefones = "outrosTelefones";
	public static final String email = "email";
	public static final String atendentelogadotemacesso = "atendenteLogadoTemAcesso";
	public static final String atendentelogadoresponsavelprincipal = "atendenteLogadoResponsavelPrincipal";
	public static final String umperfilprivado = "umPerfilPrivado";
	public static final String umperfilpublico = "umPerfilPublico";
	public static final String umperfilcompartilhado = "umPerfilCompartilhado";
	public static final String satisfacao = "satisfacao";
	public static final String relacionamento = "relacionamento";
	public static final String emailsenviadorecebido = "emailsEnviadoRecebido";
	public static final String listaapresentacoesvinculadas = "listaApresentacoesVinculadas";
	public static final String umapessoafisica = "umaPessoaFisica";
	public static final String umapessoajuridica = "umaPessoaJuridica";
	public static final String endereco = "endereco";
	public static final String cep = "CEP";
	public static final String origem = "origem";
	public static final String contatoprincipal = "contatoPrincipal";
	public static final String contatosprospecto = "contatosProspecto";
	public static final String arquivos = "arquivos";
	public static final String ultimosarquivos = "ultimosArquivos";
	public static final String localizacao = "localizacao";
	public static final String servicos = "servicos";
	public static final String ultimoorcamento = "ultimoOrcamento";
	public static final String orcamentos = "orcamentos";
	public static final String meta = "meta";
	public static final String canalrocketchat = "canalRocketChat";
	public static final String usuariosresponsaveis = "usuariosResponsaveis";
	public static final String usuariosconvidados = "usuariosConvidados";
	public static final String usuariosrespdisponiveis = "usuariosRespDisponiveis";
	public static final String relacionamentoanterior = "relacionamentoAnterior";
	public static final String usuarioresponsavel = "usuarioResponsavel";
	public static final String usuarioatendimento = "usuarioAtendimento";
	public static final String datahoracriouprospecto = "dataHoracriouProspecto";
	public static final String datahoraalterouprospecto = "dataHoraAlterouProspecto";
	public static final String datahoraultimainteracao = "dataHoraUltimaInteracao";
	public static final String usuariocriou = "usuarioCriou";
	public static final String usuarioeditou = "usuarioEditou";
	public static final String quantidadecontatos = "quantidadeContatos";
	public static final String quantidadeanexos = "quantidadeAnexos";
	public static final String quantidadeatividades = "quantidadeAtividades";
	public static final String quantidadeatividadeslead = "quantidadeAtividadesLead";
	public static final String quantidadeemailstrocados = "quantidadeEmailsTrocados";
	public static final String quantidadeemailsnaolidos = "quantidadeEmailsNaoLidos";
	public static final String atividadesexecutadas = "atividadesExecutadas";
	public static final String modoposvendas = "modoPosVendas";
	public static final String possuidemandaurgencia = "possuiDemandaUrgencia";
	public static final String datahoramudancarelacionamento = "dataHoraMudancaRelacionamento";
	public static final String atividadesrealizadas = "atividadesRealizadas";
	public static final String historicorelacionamento = "historicoRelacionamento";
	public static final String ativo = "ativo";
	public static final String linknotionintranet = "linkNotionIntranet";
	public static final String responsavel = "responsavel";
	public static final String observacao = "observacao";
	public static final String estilovisualizacao = "estiloVisualizacao";
	public static final String usuariologadosolicitouacesso = "usuarioLogadoSolicitouAcesso";
	public static final String tagsatendimento = "tagsAtendimento";
	public static final String possuiatividadesemandamento = "possuiAtividadesEmAndamento";
	public static final String clientesrelacionados = "clientesRelacionados";
	public static final String clientesquemerelacionam = "clientesQueMeRelacionam";
	public static final String emailsenviados = "emailsEnviados";
	public static final String emailsrecebidos = "emailsRecebidos";
	public static final String emailsnaoenviados = "emailsNaoEnviados";
	public static final String emailsnaolido = "emailsNaoLido";
	public static final String atividadesemandamento = "atividadesEmAndamento";
	public static final String listadadoscrm = "listaDadosCRM";
	public static final String relacionamentoscomcoletadado = "relacionamentosComColetaDado";
	public static final String listadadoscrmportiporelacionamento = "listaDadosCRMPorTipoRelacionamento";
	public static final String listadadoscoletadosnaovinculados = "listaDadosColetadosNaoVinculados";
	public static final String pertenceaousuariologado = "pertenceAoUsuarioLogado";
	public static final String camposdinamicosagrupados = "camposDinamicosAgrupados";
	public static final String ultimaatividadeemandamento = "ultimaAtividadeEmAndamento";
	public static final String docequipecategorias = "docEquipeCategorias";
	public static final String docclientecategorias = "docClienteCategorias";
	public static final String integracoeslink = "integracoesLink";
	public static final String chamadosabertos = "chamadosAbertos";
	public static final String solicitacoesabertas = "solicitacoesAbertas";
}