package br.org.carameloCode.erp.modulo.crm.api.model.pessoa;

import br.org.carameloCode.erp.modulo.crm.entidadesJPA.crm.prospecto.Pessoa;
import com.super_bits.modulosSB.SBCore.modulos.objetos.InfoCampos.anotacoes.InfoReferenciaEntidade;

@InfoReferenciaEntidade(tipoObjeto = Pessoa.class)
public enum ValoresLogicosPessoa {
	NOME, DOCUMENTO, EMAIL, ATENDENTELOGADOTEMACESSO, ATENDENTELOGADORESPONSAVELPRINCIPAL, UMPERFILPUBLICO, ENDERECO, CEP, CONTATOPRINCIPAL, ARQUIVOS, ULTIMOSARQUIVOS, LOCALIZACAO, SERVICOS, ULTIMOORCAMENTO, META, USUARIOSRESPDISPONIVEIS, RELACIONAMENTOANTERIOR, USUARIORESPONSAVEL, USUARIOATENDIMENTO, QUANTIDADECONTATOS, QUANTIDADEANEXOS, QUANTIDADEATIVIDADES, QUANTIDADEATIVIDADESLEAD, QUANTIDADEEMAILSTROCADOS, QUANTIDADEEMAILSNAOLIDOS, POSSUIDEMANDAURGENCIA, ATIVO, RESPONSAVEL, ESTILOVISUALIZACAO, USUARIOLOGADOSOLICITOUACESSO, POSSUIATIVIDADESEMANDAMENTO, PERTENCEAOUSUARIOLOGADO, CAMPOSDINAMICOSAGRUPADOS, ULTIMAATIVIDADEEMANDAMENTO, DOCEQUIPECATEGORIAS, DOCCLIENTECATEGORIAS, INTEGRACOESLINK
}