package br.org.carameloCode.erp.modulo.crm.api.model.envioemailatividade;

import br.org.carameloCode.erp.modulo.crm.entidadesJPA.mail.envioEmail.envioDocumentoAtividade.EnvioEmailAtividade;
import com.super_bits.modulosSB.SBCore.modulos.objetos.InfoCampos.anotacoes.InfoReferenciaEntidade;

@InfoReferenciaEntidade(tipoObjeto = EnvioEmailAtividade.class)
public enum ValoresLogicosEnvioEmailAtividade {
	CONTATOSDISPONIVEIS, ARQUIVOSANEXADOS, ARQUIVOSDISPONIVEIS, FOILIDOPELODESTINATARIO, HTMLMAILCAMPOPARAJSON, HTMLMAILCAMPOEMCOPIAJSON, TEXTO, UMEMAILRECEBIDO, UMEMAILDEATIVIDADE, UMEMAILMODORASCUNHO, UMEMAILPRIVADO, UMEMAILCOMPARTILHADO, UMEMAILDEPROSPECTO, UMACONVERSAEXTERNA, UMACONVERSAINTERNA, UMEMAILRESPOSTA, UMEMAILPASSIVO, UMEMAILATIVO, ARQUIVOS, CONTEUDOHTMLPROCESSADO, ICONETIPOEMAIL, ICONEALERTA, CORTIPOEMAIL, ACOESDISPONIVEIS
}