package br.org.carameloCode.erp.modulo.crm.api.model.pessoajuridica;

import br.org.carameloCode.erp.modulo.crm.entidadesJPA.prospecto.PessoaJuridica;
import com.super_bits.modulosSB.SBCore.modulos.objetos.InfoCampos.anotacoes.InfoReferenciaEntidade;

@InfoReferenciaEntidade(tipoObjeto = PessoaJuridica.class)
public enum ValoresLogicosPessoaJuridica {
	SITE, ARQUIVOSENVIADOS, ARQUIVOSRECEBIDOS, NOME, DOCUMENTO, EMAIL, ATENDENTELOGADOTEMACESSO, ATENDENTELOGADORESPONSAVELPRINCIPAL, UMPERFILPUBLICO, ENDERECO, CONTATOPRINCIPAL, ARQUIVOS, ULTIMOSARQUIVOS, LOCALIZACAO, SERVICOS, ULTIMOORCAMENTO, META, USUARIOSRESPONSAVEIS, USUARIOSRESPDISPONIVEIS, RELACIONAMENTOANTERIOR, USUARIORESPONSAVEL, USUARIOATENDIMENTO, QUANTIDADECONTATOS, QUANTIDADEANEXOS, QUANTIDADEATIVIDADES, QUANTIDADEATIVIDADESLEAD, QUANTIDADEEMAILSTROCADOS, QUANTIDADEEMAILSNAOLIDOS, POSSUIDEMANDAURGENCIA, ATIVO, RESPONSAVEL, ESTILOVISUALIZACAO, USUARIOLOGADOSOLICITOUACESSO, POSSUIATIVIDADESEMANDAMENTO, PERTENCEAOUSUARIOLOGADO, CAMPOSDINAMICOSAGRUPADOS, ULTIMAATIVIDADEEMANDAMENTO, DOCEQUIPECATEGORIAS, DOCCLIENTECATEGORIAS, INTEGRACOESLINK
}